// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo3Cf90j3CjgOMuXPKYwGx5id0cf9tUFA',
    appId: '1:756867061198:web:277bf9557257accc09479f',
    messagingSenderId: '756867061198',
    projectId: 'tiers-22911',
    authDomain: 'tiers-22911.firebaseapp.com',
    storageBucket: 'tiers-22911.appspot.com',
    measurementId: 'G-C7E0S67F4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzAvT_eCUR6IahVMk5N5icSCZMYNOQxeE',
    appId: '1:756867061198:android:3cfb07642ca64fdf09479f',
    messagingSenderId: '756867061198',
    projectId: 'tiers-22911',
    storageBucket: 'tiers-22911.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1GndhZZMxhYUzu8FcF4B4Hq2XqvrpJi8',
    appId: '1:756867061198:ios:fd2d9a8c45d4985309479f',
    messagingSenderId: '756867061198',
    projectId: 'tiers-22911',
    storageBucket: 'tiers-22911.appspot.com',
    iosBundleId: 'com.example.tiersFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1GndhZZMxhYUzu8FcF4B4Hq2XqvrpJi8',
    appId: '1:756867061198:ios:fd2d9a8c45d4985309479f',
    messagingSenderId: '756867061198',
    projectId: 'tiers-22911',
    storageBucket: 'tiers-22911.appspot.com',
    iosBundleId: 'com.example.tiersFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo3Cf90j3CjgOMuXPKYwGx5id0cf9tUFA',
    appId: '1:756867061198:web:fd4eaa3da64287e909479f',
    messagingSenderId: '756867061198',
    projectId: 'tiers-22911',
    authDomain: 'tiers-22911.firebaseapp.com',
    storageBucket: 'tiers-22911.appspot.com',
    measurementId: 'G-R6L64GJRZ2',
  );
}
